### ISSUE TITLE
VSCode Debugging and Code Coverage

### ISSUE THREAD

**Issue by Paruun** [igniteram/protractor-cucumber-typescript#29]
Would someone be able to provide a clean way of adding code coverage as well as debugging functionality from VSCode (with map files to enable typescript debugging).

**Comment by igniteram** [comment]
Sometime back I wrote the documentation for vscode debugging, it was merged in the protractor repo : http://www.protractortest.org/#/debugging#setting-up-vscode-for-debugging
Generally code coverage is not done for e2e tests but you could checkout [istanbul](https://github.com/gotwarlost/istanbul) not sure it would work with Typescript.

Since this is more of a support question and not an issue with this project , I am closing close it. Feel free to raise a new one!
