### ISSUE TITLE
ElementArrayFinder

### ISSUE THREAD

**Issue by skullz03** [igniteram/protractor-cucumber-typescript#49]
Not an issue per say; but I was curious how you would return an array of elements in the existing page object structure that you have. I took a stab at it by adding 2 new locators to the below snippet from your page objects. Please let me know what you think?

```
import { $, ElementFinder } from "protractor";
export class SearchPageObject {
    public searchTextBox: ElementFinder;
    public searchButton: ElementFinder;
    public logo: ElementFinder;
    public this.table_rows: ElementArrayFinder

    constructor() {
        this.searchTextBox = $("#lst-ib");
        this.searchButton = $("input[value='Google Search']");
        this.logo = $('div#logocont');
        this.table_rows = element.all('.table > tr');
        this.table_columns = this.table_rows.$$('td');
    }
}
```

Does this look ok to you? I tried this structure in order to get the rows of a table and then drill to columns and then print out the columns text but wasn't successful. So, thought I'd ask you where you think I am going wrong.

**Comment by igniteram** [comment]
@skullz03 `element.all` returns an array of all matching elements so in your case it would fetch all `tr` tags in `table` class, now if you are chaining with another element array finder i.e. trying to find columns, what it is actually doing is first getting all table rows in the DOM and then trying to find all the columns of those rows but it doesn't know which row it should find with, that is the reason it was unsuccessfull.

I would advice first find all the the rows and then loop each of the rows using `each()` function or normal `forEach()` loop and then try to find the columns of that particular row.

In future pls ask such questions in Stackoverflow or Protractor;s Gitter channel, since this is a support question I am closing this issue!
